config/routes.rb
VirtualTreasureHuntServer::Application.routes.draw do
  resources :assets
  resources :users
  
  root :to => "admin#index"

end

app/models/asset.rb
class Asset < ActiveRecord::Base

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
    @title = "Virtual Treasure Hunt Server Admin"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  # GET /assets
  # GET /assets.xml
  def index
    @sidebar_title = "Available Assets"
    
    @onload = "initialize()"
    
    @assets = Asset.all #(:select => [:id,:latitude,:longitude, :name, :description])
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { @assets }
      format.json { render :json => @assets }
      
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    @sidebar_title = "Asset Details"
    
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.js # show.html.erb
      format.xml  { render :layout => false }
      format.json { render :json => @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.xml
  def new
    @sidebar_title = "New Asset"
    
    @asset = Asset.new
    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @sidebar_title = "Edit Asset"
    
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.xml
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to(@asset, :notice => 'Asset was successfully created.') }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.js
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to(assets_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1><%= @title %></h1>

<%= link_to "Manage Users", :controller => "users", :action => "index" %>
<br/></br/>
<%= link_to "Mange Assets", :controller => "assets", :action => "index" %>

app/views/assets/_form.html.erb
<h2><%= @sidebar_title %></h2>

<%= form_for(@asset, :remote=>true) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :remaining %><br />
    <%= f.text_field :remaining %>
  </div>
  <div class="field">
    <%= f.label :hits %><br />
    <%= f.text_field :hits %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/_list.html.erb
<h2><%= @sidebar_title %></h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= link_to asset.name, asset, :remote => true %></td>

        <td><%= link_to 'Edit', edit_asset_path(asset), :remote => true %></td>
        <td><%= link_to 'Destroy', asset, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= link_to 'New Asset', new_asset_path, :remote => true %>

app/views/assets/_show.html.erb
<h2><%= @sidebar_title %></h2>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @asset.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @asset.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @asset.longitude %>
</p>

<p>
  <b>Description:</b>
  <%= @asset.description %>
</p>
<p>
  <b>Remaining:</b>
  <%= @asset.remaining %>
</p>

<p>
  <b>Hits:</b>
  <%= @asset.hits %>
</p>


<%= link_to 'Edit', edit_asset_path(@asset), :remote => true %> |
<%= link_to 'Back', assets_path, :remote => true %>

app/views/assets/index.html.erb
<h1>Administer Assets</h1>
<script>
  markers = <%= raw ActiveSupport::JSON.encode(@assets) %>
</script>

<div id="map_canvas"></div>

<div id="sidebar">
  <%= render 'list' %>  
</div>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @asset.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @asset.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @asset.longitude %>
</p>

<p>
  <b>Description:</b>
  <%= @asset.description %>
</p>
<p>
  <b>Remaining:</b>
  <%= @asset.remaining %>
</p>

<p>
  <b>Hits:</b>
  <%= @asset.hits %>
</p>


<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <%= link_to "About" %> |
  <%= link_to "F.A.Q" %> |
  <%= link_to "Help" %>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  
  <div id="user-nav">
    Signed in as <strong>admin</strong> |
    <%= link_to "Administer Users", users_path, :class => :admin %> |
    <%= link_to "Edit Profile" %> |
    <%= link_to "Logout" %>
  </div>
  
  <div id="site-nav">
    <%= link_to "Home" %> |
    <%= link_to "Administer Assets", assets_path, :class => :admin %> |
    <%= link_to "Stats", "#", :class => :admin %> |
    <%= link_to "My Collected Assets", "#" %>
  </div>
  
</div>

app/views/layouts/_stylesheets.html.erb
<!--%= stylesheet_link_tag :all %-->
<link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/stylesheets/blueprint/print.css" type="text/css" media="print">
<!--[if lt IE 8]>
  <link rel="stylesheet" href="/stylesheets/blueprint/ie.css" type="text/css" media="screen, projection">
<![endif]-->
<link href="/stylesheets/custom.css" media="screen" rel="stylesheet" type="text/css" /> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualTreasureHuntServer</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false" ></script>
  <%= csrf_meta_tag %>
</head>
<body <%= "onload=#{@onload}" %>>
  
<%= render 'layouts/header' %>

<div id="content">
  <%= yield %>
</div>
  
<%= render 'layouts/footer' %>
  
</body>
</html>

app/views/users/index.html.erb
Users